# Generated by Django 2.1.3 on 2018-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AUTO', models.CharField(max_length=15)),
                ('codigo_returno', models.CharField(max_length=3)),
                ('mensagem_retorno', models.CharField(max_length=200)),
                ('hora', models.CharField(max_length=10)),
                ('mensagem_envio', models.CharField(max_length=200)),
                ('date_file', models.CharField(max_length=10)),
            ],
        ),
    ]
